version: "3.9"
services:
  bot:
    build: .
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: bash -c "yarn install && yarn run dev"
    networks:
      - br0
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/init.d:/docker-entrypoint-initdb.d
    networks:
      - br0
    environment:
      - MYSQL_ROOT_PASSWORD=kidahirokazu
      - MYSQL_DATABASE=ayaka
      - MYSQL_USER=ayaka
      - MYSQL_PASSWORD=ayaka
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/errorpages:/usr/share/nginx/errorpages
    networks:
      - br0
    depends_on:
      - bot

volumes:
  db:
  nginx:

networks:
  br0:
    driver: bridge
