version: "3.9"
services:
  bot:
    image: node:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash -c "yarn install && yarn run dev"
    networks:
      - br0
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    ports:
      - 3307:3306
    volumes:
      - "./db/data:/var/lib/mysql"
      - "./db/data/init.d:/docker-entrypoint-initdb.d"
    networks:
      - br0
    environment:
      - MYSQL_ROOT_PASSWORD=kidahirokazu
      - MYSQL_DATABASE=ayaka
      - MYSQL_USER=ayaka
      - MYSQL_PASSWORD=ayaka
volumes:
  db:

networks:
  br0:
    driver: bridge
