version: "3.9"
services:
  bot:
    build: ./dockerfiles/bot
    ports:
      - 8080:3000
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules:/app/node_modules
      - ${MNTPOINT}:/userData
    working_dir: /app
    command: bash -c "yarn install && yarn run dev"
    environment:
      TZ: Asia/Tokyo
    networks:
      - br0
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    networks:
      - br0
    environment:
      - MYSQL_DATABASE=ayaka
      - MYSQL_USER=ayaka
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}

  nginx:
    build: ./dockerfiles/nginx
    restart: always
    ports:
      - 80:80
    networks:
      - br0
    depends_on:
      - bot

volumes:
  node_modules:
    driver: local
  db-data:
    driver: local

networks:
  br0:
    driver: bridge
