version: "3.9"
services:
  bot:
    build: .
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules:/app/node_modules
    working_dir: /app
    command: bash -c "yarn install && yarn run dev"
    environment:
      TZ: Asia/Tokyo
    networks:
      - br0
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    networks:
      - br0
    environment:
      - MYSQL_ROOT_PASSWORD=kidahirokazu
      - MYSQL_DATABASE=ayaka
      - MYSQL_USER=ayaka
      - MYSQL_PASSWORD=ayaka

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/errorpages:/usr/share/nginx/errorpages
    networks:
      - br0
    depends_on:
      - bot

volumes:
  node_modules:
    driver: local
  db-data:
    driver: local

networks:
  br0:
    driver: bridge
