# docker-compose.yaml
version: "3.9"
services:
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./data/nginx:/var/log/nginx
      - ./nginx:/var/www/html
