version: "3.9"
services:
  bot:
    build: ./dockerfiles/bot
    restart: on-failure
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - node_modules:/app/node_modules
      - ${MNTPOINT}:/userData
    working_dir: /app
    command: bash -c "yarn install && yarn run dev"
    environment:
      TZ: Asia/Tokyo
    network_mode: "host"
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ./db/init.d:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-data:/var/lib/mysql
    network_mode: "host"
    environment:
      - MYSQL_DATABASE=ayaka
      - MYSQL_USER=ayaka
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}

volumes:
  node_modules:
    driver: local
  db-data:
    driver: local
